//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daaamn
{
    using System;
    using System.Collections.Generic;
    
    public partial class klient
    {
        public string FIO { get; set; }
        public string code { get; set; }
        public string pasport { get; set; }
        public System.DateTime date { get; set; }
        public string adress { get; set; }
        public string mail { get; set; }
        public string pass { get; set; }
    }
}
