//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daaamn
{
    using System;
    using System.Collections.Generic;
    
    public partial class sotrydnic
    {
        public string code { get; set; }
        public string dolzh { get; set; }
        public string FIO { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public string last_vhod { get; set; }
        public string type_vhod { get; set; }
    }
}
