//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daaamn
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz
    {
        public int id { get; set; }
        public string code_zakaza { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public string code_klient { get; set; }
        public string yslygi { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date_off { get; set; }
        public string time_prokat { get; set; }
    }
}
